name: FUJI
test_as_valid: true
manual_seed: 3407 # is all you need
output: runs

loss:
  types:
  - L1 #pred_rgb & gt_rgb
  - L1 #pred_raw & gt_raw
  weights:
  - 1.0
  - 1.0

data:
  name: SIDFujiDataset
  data_dir: /data/dataset/Carlos/SID/Fuji
  num_workers: 16
  pin_memory: true
  process:
    max_clip: 1.0
    min_clip: 0.0
    transpose: true
    h_flip: true
    v_flip: true
  test:
    batch_size: 1
    image_list_file: Fuji_test_list.txt
    merge_test: true
  train:
    batch_size: 1
    image_list_file: Fuji_train_list.txt
    patch_size: 384
  valid:
    batch_size: 1
    image_list_file: Fuji_val_list.txt

model:
  name: TSCDNet
  TSCDNet:
    in_channels: 9
    base_channels: 32
    base_d_state: 4

train:
  base_lr: 1.0e-4
  last_lr_epoch: 200
  clip_grad: 0.1
  epochs: 250
  lr_scheduler:
    type: cosine
  optimizer: 
    type: adamw
    eps: 1.0e-8
    betas: [0.9, 0.999]
  min_lr: 1.0e-5
  start_epoch: 0
  weight_decay: 0
  warmup_epochs: 0

