name: MCR
test_as_valid: true
manual_seed: 3407
output: runs

loss:
  types:
  - L1 #pred_rgb & gt_rgb
  - L1 #pred_raw & gt_raw
  weights:
  - 1.0
  - 1.0

data:
  name: MCRDataset
  data_dir: E:/Deep Learning/datasets/MCR
  num_workers: 16
  pin_memory: true
  process:
    max_clip: 1.0
    min_clip: 0.0
    transpose: true
    h_flip: true
    v_flip: true
  test:
    image_list_file: MCR_test_list.txt
    batch_size: 1
    patch_size: null
  train:
    image_list_file: MCR_train_list.txt
    batch_size: 1
    patch_size: null

model:
  name: TSCDNet
  TSCDNet:
    in_channels: 4
    base_channels: 32
    base_d_state: 4

train:
  base_lr: 1.0e-4
  last_lr_epoch: 200
  clip_grad: 0.1
  epochs: 250
  lr_scheduler:
    type: cosine
  optimizer: 
    type: adamw
    eps: 1.0e-8
    betas: [0.9, 0.999]
  min_lr: 1.0e-5
  start_epoch: 0
  weight_decay: 0
  warmup_epochs: 0
